### ISSUE TITLE
API responding with 400 error

### ISSUE THREAD

**Issue by pauladams24** [cloudflare/cloudflare-php#75]
I am new to the Cloudflare SDK and have tried using the test script (obtains the user's ID) as shown on https://support.cloudflare.com/hc/en-us/articles/115001661191
but get the following error:
`Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: 'GET https://api.cloudflare.com/client/v4/user' resulted in a '400 Bad Request' response: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Inval (truncated...) in /home/thecode1/web/api.thecoderszone.com/public_html/v2/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /home/thecode1/web/api.thecoderszone.com/public_html/v2/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /home/thecode1/web/api.thecoderszone.com/public_html/v2/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /home/thecode1/web/api.thecoderszone.com/public_html/v2/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array) # in /home/thecode1/web/api.thecoderszone.com/public_html/v2/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113'`

I don't understand why I am getting an error 400, but I think my API key is correct as it works through curl.

**Comment by pauladams24** [comment]
A credentials issue on my part. Please ignore this issue.
